# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"

  # Allows manual trigger from the Actions tab
  workflow_dispatch:

permissions:
  contents: write   # ðŸ‘ˆ required to allow pushing to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@v4

      # Generate the snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ryankelly-44
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Show status for debugging
      - run: git status

      # Deploy to the 'output' branch
      - name: Push Snake Animation to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
